name: Git Command Test

on: workflow_dispatch

jobs:
  settings_test:
    runs-on: ubuntu-latest

    name: Configure Runner
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Checkout
        uses: actions/checkout@v3


      - name: Git Commands
        run:  |
          git status
          git pull
          git checkout test
          git status
          

