name: Settings Test 2

on: workflow_dispatch

jobs:
  settings_test:
    runs-on: ubuntu-latest

    name: Configure Runner
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Read settings.xml file
        run: cat /home/runner/.m2/settings.xml

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0

      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: maven-settings-action
        uses: s4u/maven-settings-action@v2.8.0
        with:
            servers: |
              [
                {
                "id": "TEST",
                "username": "TESTUSERNAME",
                "password": "TESTPASSWORD"
                }
              ]   
            githubServer: false

      - name: Read settings.xml file
        run: cat /home/runner/.m2/settings.xml


      - name: Adding Lines To settings.xml file
        run: |
          sed '4i\  <remote_connection_protocol>sftp</remote_connection_protocol>\n  <ftp_destination_ip>0.0.0.0</ftp_destination_ip>' settings.xml
          cat /home/runner/.m2/settings.xml
          cat settings.xml

      - name: Read settings.xml file
        run: cat /home/runner/.m2/settings.xml
