name: Settings Test
on: workflow_dispatch

jobs:
  settings_test:
    runs-on: ubuntu-latest

    name: Configure Runner
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Read settings.xml file
        run: cat /home/runner/.m2/settings.xml

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0

      - name: Checkout Main Branch
        uses: actions/checkout@v3

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          profiles: |
            [{"profile": 
                {
                 "activation": {
                   "activeByDefault": true
                 },
                 "repositories": {
                   "repository": [
                     {
                       "id": "central",
                       "name": "maven central",
                       "url": "https://repo1.maven.org/maven2"
                     },
                     {
                       "id": "test-repository",
                       "name": "test-repository-name",
                       "url": "http://some.repository.url"
                     }
                   ]
                 }
               }
            }]
          output_file: .m2/settings.xml
      - name: Read settings.xml file
        run: cat /home/runner/.m2/settings.xml
